import os
from datetime import datetime, timedelta
from typing import Optional

from loguru import logger
from sqlalchemy.exc import IntegrityError
from sqlmodel import Session, select

from app.db import get_engine
from app.models.content import (
    ContentCampaign,
    ContentClient,
    ContentPiece,
    ContentPieceCreate,
    ContentPieceStatus,
    ContentTenant,
    EntitlementStatus,
)
from app.services.content import audit
from app.services.content import generation_templates as templates_service
from app.services.content import pieces as pieces_service

TICK_SECONDS = float(os.environ.get("CONTENT_AUTOMATION_TICK_SECONDS", 300))
_BATCH_LIMIT = int(os.environ.get("CONTENT_AUTOMATION_BATCH_SIZE", 50))


def next_slot(max_scheduled: Optional[datetime], *, now: datetime) -> datetime:
    """The next calendar slot for a campaign's proactive generation.

    Pure and stateless: the caller supplies the current max `scheduled_for`
    among the campaign's non-terminal pieces (or None when there are none).
    """
    if max_scheduled is None:
        return now
    return max_scheduled + timedelta(days=1)


def pick_template_index(autogenerated_count: int, template_count: int) -> int:
    """Round-robin index into a campaign's template list.

    `template_count` must be >= 1 — callers already skip campaigns with no
    templates before reaching this function.
    """
    return autogenerated_count % template_count


def _tenant_for_campaign(session: Session, campaign: ContentCampaign) -> Optional[ContentTenant]:
    client = session.get(ContentClient, campaign.client_id)
    if client is None:
        return None
    return session.get(ContentTenant, client.tenant_id)


def _fill_campaign_calendars(session: Session, *, batch_limit: int) -> None:
    """Passe 1: cria, no máximo, uma piece por campanha elegível neste tick.

    Preenchimento gradual — não o horizonte inteiro de uma vez — para não
    gerar um pico de trabalho de geração. Uma campanha nova leva vários ticks
    até o calendário ficar cheio; comportamento pretendido, não um bug.
    """
    campaigns = session.exec(
        select(ContentCampaign)
        .where(ContentCampaign.status == "active")
        .limit(batch_limit)
    ).all()

    for campaign in campaigns:
        tenant = _tenant_for_campaign(session, campaign)
        if tenant is None or tenant.entitlement_status != EntitlementStatus.active:
            continue

        templates = templates_service.list_templates(
            session, tenant_id=tenant.id, campaign_id=campaign.id
        )
        if not templates:
            continue

        max_scheduled = session.exec(
            select(ContentPiece.scheduled_for)
            .where(
                ContentPiece.campaign_id == campaign.id,
                ContentPiece.status.not_in(
                    [ContentPieceStatus.rejected, ContentPieceStatus.failed]
                ),
            )
            .order_by(ContentPiece.scheduled_for.desc())
        ).first()
        slot = next_slot(max_scheduled, now=datetime.utcnow())
        if slot >= datetime.utcnow() + timedelta(days=campaign.horizon_days):
            continue

        autogenerated_count = len(
            session.exec(
                select(ContentPiece.id).where(
                    ContentPiece.campaign_id == campaign.id,
                    ContentPiece.is_autogenerated == True,  # noqa: E712
                )
            ).all()
        )
        template = templates[pick_template_index(autogenerated_count, len(templates))]

        piece_create = ContentPieceCreate(
            campaign_id=campaign.id,
            type=template.type,
            idempotency_key=f"auto:{campaign.id}:{slot.date().isoformat()}",
            is_synthetic_media=template.is_synthetic_media,
            generation_prompt=template.generation_prompt,
            avatar_id=template.avatar_id,
            voice_id=template.voice_id,
            content_category=template.content_category,
            aspect_ratio=template.aspect_ratio,
            resolution=template.resolution,
            duration=template.duration,
        )
        try:
            piece, created = pieces_service.create_piece(
                session, tenant_id=tenant.id, payload=piece_create
            )
        except IntegrityError:
            # Outra réplica já criou a piece para este campaign_id + slot
            # (mesma UniqueConstraint que resolve_publication_request usa na
            # fase 3) — corrida normal entre réplicas, não um erro.
            session.rollback()
            logger.debug(
                f"campaign {campaign.id}: concurrent auto-generation for slot "
                f"{slot.date().isoformat()} — another replica won the race"
            )
            continue

        if not created:
            continue

        piece.scheduled_for = slot
        piece.is_autogenerated = True
        session.add(piece)
        session.commit()
        audit.write_audit_log(
            session,
            tenant_id=tenant.id,
            entity_type="content_piece",
            entity_id=piece.id,
            action="autogenerated",
            actor="system:automation_scheduler",
        )
