import os
import threading
from datetime import datetime, timedelta
from typing import Optional

from loguru import logger
from sqlalchemy import func
from sqlalchemy.exc import IntegrityError
from sqlmodel import Session, select, update

from app.db import get_engine
from app.models.content import (
    ApprovalAction,
    ContentCampaign,
    ContentCategory,
    ContentClient,
    ContentPiece,
    ContentPieceCreate,
    ContentPieceStatus,
    ContentSocialAccount,
    ContentTenant,
    EntitlementStatus,
    RiskLevel,
)
from app.models.content_publishing import ContentSocialPublication
from app.services.content import approval_rules as approval_rules_service
from app.services.content import audit
from app.services.content import generation_templates as templates_service
from app.services.content import pieces as pieces_service
from app.services.content import publications as publications_service

TICK_SECONDS = float(os.environ.get("CONTENT_AUTOMATION_TICK_SECONDS", 300))
_BATCH_LIMIT = int(os.environ.get("CONTENT_AUTOMATION_BATCH_SIZE", 50))


def next_slot(max_scheduled: Optional[datetime], *, now: datetime) -> datetime:
    """The next calendar slot for a campaign's proactive generation.

    Pure and stateless: the caller supplies the current max `scheduled_for`
    among the campaign's non-terminal pieces (or None when there are none).
    """
    if max_scheduled is None:
        return now
    return max_scheduled + timedelta(days=1)


def pick_template_index(autogenerated_count: int, template_count: int) -> int:
    """Round-robin index into a campaign's template list.

    `template_count` must be >= 1 — callers already skip campaigns with no
    templates before reaching this function.
    """
    return autogenerated_count % template_count


def _tenant_for_campaign(session: Session, campaign: ContentCampaign) -> Optional[ContentTenant]:
    client = session.get(ContentClient, campaign.client_id)
    if client is None:
        return None
    return session.get(ContentTenant, client.tenant_id)


def _fill_campaign_calendars(session: Session, *, batch_limit: int) -> None:
    """Passe 1: cria, no máximo, uma piece por campanha elegível neste tick.

    Preenchimento gradual — não o horizonte inteiro de uma vez — para não
    gerar um pico de trabalho de geração. Uma campanha nova leva vários ticks
    até o calendário ficar cheio; comportamento pretendido, não um bug.
    """
    campaigns = session.exec(
        select(ContentCampaign)
        .where(ContentCampaign.status == "active")
        # Sem ORDER BY, o LIMIT não garante rotação: com mais campanhas
        # elegíveis que _BATCH_LIMIT, o Postgres pode devolver sempre o mesmo
        # subconjunto e as demais nunca chegariam a ser processadas.
        .order_by(ContentCampaign.id)
        .limit(batch_limit)
    ).all()

    for campaign in campaigns:
        try:
            tenant = _tenant_for_campaign(session, campaign)
            if tenant is None or tenant.entitlement_status != EntitlementStatus.active:
                continue

            templates = templates_service.list_templates(
                session, tenant_id=tenant.id, campaign_id=campaign.id
            )
            if not templates:
                continue

            max_scheduled = session.exec(
                select(ContentPiece.scheduled_for)
                .where(
                    ContentPiece.campaign_id == campaign.id,
                    ContentPiece.status.not_in(
                        [ContentPieceStatus.rejected, ContentPieceStatus.failed]
                    ),
                    # Pieces criadas manualmente pela API nunca têm slot de
                    # calendário. Sem este filtro, um único NULL contamina o
                    # ORDER BY ... DESC (no Postgres, NULLS FIRST é o padrão)
                    # e o calendário automático da campanha trava para sempre.
                    ContentPiece.scheduled_for.is_not(None),
                )
                .order_by(ContentPiece.scheduled_for.desc())
            ).first()
            slot = next_slot(max_scheduled, now=datetime.utcnow())
            if slot >= datetime.utcnow() + timedelta(days=campaign.horizon_days):
                continue

            autogenerated_count = session.exec(
                select(func.count(ContentPiece.id)).where(
                    ContentPiece.campaign_id == campaign.id,
                    ContentPiece.is_autogenerated == True,  # noqa: E712
                )
            ).one()
            template = templates[pick_template_index(autogenerated_count, len(templates))]

            piece_create = ContentPieceCreate(
                campaign_id=campaign.id,
                type=template.type,
                idempotency_key=f"auto:{campaign.id}:{slot.date().isoformat()}",
                is_synthetic_media=template.is_synthetic_media,
                generation_prompt=template.generation_prompt,
                narration_script=template.narration_script,
                avatar_id=template.avatar_id,
                voice_id=template.voice_id,
                content_category=template.content_category,
                aspect_ratio=template.aspect_ratio,
                resolution=template.resolution,
                duration=template.duration,
            )
            try:
                piece, created = pieces_service.create_piece(session, payload=piece_create)
            except IntegrityError:
                # Outra réplica já criou a piece para este campaign_id + slot
                # (mesma UniqueConstraint que resolve_publication_request usa na
                # fase 3) — corrida normal entre réplicas, não um erro.
                session.rollback()
                logger.debug(
                    f"campaign {campaign.id}: concurrent auto-generation for slot "
                    f"{slot.date().isoformat()} — another replica won the race"
                )
                continue

            if not created:
                continue

            piece.scheduled_for = slot
            piece.is_autogenerated = True
            session.add(piece)
            session.commit()
            audit.write_audit_log(
                session,
                tenant_id=tenant.id,
                entity_type="content_piece",
                entity_id=piece.id,
                action="autogenerated",
                actor="system:automation_scheduler",
            )
        except Exception:
            # Uma campanha problemática não pode derrubar o passe inteiro —
            # sem isso ela vira um "poison pill" que se repete a cada tick.
            session.rollback()
            logger.exception(
                f"campaign {getattr(campaign, 'id', None)}: proactive generation failed"
            )
            continue


_SUPPORTED_CONDITION_KEYS = {"content_category", "risk_level"}


def rule_matches(
    condition: dict, *, content_category: Optional[ContentCategory], risk_level: RiskLevel
) -> bool:
    """A rule's `condition` matches a piece's fields.

    Every key present in `condition` must match — AND semantics, not OR. An
    empty condition matches anything (catch-all fallback rule). An
    unsupported key (only content_category/risk_level are wired) never
    matches: a typo'd or future key must fall through to require_review, not
    silently match everything.
    """
    piece_values = {
        "content_category": content_category.value if content_category else None,
        "risk_level": risk_level.value,
    }
    for key, allowed_values in condition.items():
        if key not in _SUPPORTED_CONDITION_KEYS:
            return False
        if piece_values[key] not in allowed_values:
            return False
    return True


def _client_for_piece(session: Session, piece: ContentPiece) -> Optional[ContentClient]:
    """O client dono da piece, ou None se a cadeia de FKs estiver quebrada.

    Mesma disciplina de `_tenant_for_campaign`: um campaign_id órfão (FK
    pendente, corrida com um delete) não pode virar AttributeError.
    """
    campaign = session.get(ContentCampaign, piece.campaign_id)
    if campaign is None:
        logger.warning(
            f"piece {piece.id}: campaign {piece.campaign_id} not found — skipping"
        )
        return None
    client = session.get(ContentClient, campaign.client_id)
    if client is None:
        logger.warning(
            f"piece {piece.id}: client {campaign.client_id} not found — skipping"
        )
        return None
    return client


def _decide_approval_action(
    session: Session, piece: ContentPiece
) -> Optional[tuple[ApprovalAction, bool]]:
    """Retorna (approval_action, auto_approved), ou None se a piece for órfã."""
    if piece.requires_human_review:
        return ApprovalAction.require_review, False

    client = _client_for_piece(session, piece)
    if client is None:
        return None
    rules = approval_rules_service.list_approval_rules(
        session, tenant_id=client.tenant_id, campaign_id=piece.campaign_id
    )
    for rule in rules:
        if rule_matches(
            rule.condition, content_category=piece.content_category, risk_level=piece.risk_level
        ):
            return rule.action, rule.action == ApprovalAction.auto_approve
    return ApprovalAction.require_review, False


def _evaluate_pending_approvals(session: Session, *, batch_limit: int) -> None:
    """Passe 2: decide auto_approve/require_review para pieces ainda não avaliadas.

    Sem lock: avaliar a mesma piece duas vezes numa corrida rara entre
    réplicas é determinístico e sem efeito colateral externo. A guarda que
    importa é a escrita condicional abaixo, que protege contra uma corrida
    real (o motor decidindo ao mesmo tempo que um humano rejeita a piece).
    """
    pieces = session.exec(
        select(ContentPiece)
        .where(
            ContentPiece.status == ContentPieceStatus.pending_approval,
            ContentPiece.approval_action.is_(None),
        )
        # Tie-breaker estável: garante que, com mais pieces elegíveis que o
        # batch, todas acabem processadas em rotação (mais antigas primeiro).
        .order_by(ContentPiece.id)
        .limit(batch_limit)
    ).all()

    for piece in pieces:
        try:
            decision = _decide_approval_action(session, piece)
            if decision is None:
                continue
            action, auto_approved = decision
            values = {"approval_action": action, "updated_at": datetime.utcnow()}
            if auto_approved:
                values["status"] = ContentPieceStatus.approved
                values["approved_at"] = datetime.utcnow()

            result = session.exec(
                update(ContentPiece)
                .where(
                    ContentPiece.id == piece.id,
                    ContentPiece.status == ContentPieceStatus.pending_approval,
                )
                .values(**values)
            )
            session.commit()
            if result.rowcount == 0:
                logger.debug(
                    f"piece {piece.id} status changed concurrently — dropping "
                    f"approval-engine decision"
                )
                continue

            client = _client_for_piece(session, piece)
            if client is None:
                continue
            audit.write_audit_log(
                session,
                tenant_id=client.tenant_id,
                entity_type="content_piece",
                entity_id=piece.id,
                action=f"approval_action:{action.value}",
                actor="system:approval_engine",
            )
        except Exception:
            # Uma piece problemática não pode derrubar o passe inteiro.
            session.rollback()
            logger.exception(
                f"piece {getattr(piece, 'id', None)}: approval evaluation failed"
            )
            continue


def _dispatch_scheduled_publications(session: Session, *, batch_limit: int) -> None:
    """Passe 3: dispara resolve_publication_request uma vez por piece devida.

    O NOT EXISTS é a fronteira entre este motor (S4) e o executor da fase 3
    (S3): depois que a primeira linha de content_social_publications existe
    para uma piece, o ciclo de vida inteiro (retry, sucesso, falha) já é
    responsabilidade só da fase 3 — este passe nunca mais toca essa piece.
    """
    now = datetime.utcnow()
    due_piece_ids_subquery = (
        select(ContentSocialPublication.content_piece_id).distinct()
    )
    pieces = session.exec(
        select(ContentPiece)
        .where(
            ContentPiece.status == ContentPieceStatus.approved,
            ContentPiece.scheduled_for.is_not(None),
            ContentPiece.scheduled_for <= now,
            ContentPiece.id.not_in(due_piece_ids_subquery),
        )
        # Tie-breaker estável: sem ele, um LIMIT sob carga pode devolver
        # sempre as mesmas linhas e deixar as demais em inanição.
        .order_by(ContentPiece.id)
        .limit(batch_limit)
    ).all()

    for piece in pieces:
        try:
            client = _client_for_piece(session, piece)
            if client is None:
                continue
            tenant = session.get(ContentTenant, client.tenant_id)
            if tenant is None or tenant.entitlement_status != EntitlementStatus.active:
                continue

            accounts = session.exec(
                select(ContentSocialAccount).where(
                    ContentSocialAccount.client_id == client.id,
                    ContentSocialAccount.status == "active",
                )
            ).all()
            if not accounts:
                continue

            try:
                accepted, rejected = publications_service.resolve_publication_request(
                    session, piece=piece, social_account_ids=[account.id for account in accounts]
                )
            except IntegrityError:
                # Outra réplica já enfileirou este par piece/conta (mesma
                # UniqueConstraint(content_piece_id, social_account_id) que a
                # fase 3 já protege) — corrida normal entre réplicas.
                session.rollback()
                logger.debug(
                    f"piece {piece.id}: concurrent scheduled-publish dispatch — "
                    f"another replica won the race"
                )
                continue

            if not accepted and rejected:
                # Nenhuma linha em content_social_publications foi criada, então
                # a guarda NOT IN acima nunca vai excluir esta piece: ela seria
                # redisparada em todo tick, para sempre e em silêncio. Não dá
                # para resolver sozinho (falta asset final, plataforma
                # incompatível, etc.), mas tem que ficar visível e auditável.
                logger.warning(
                    f"piece {piece.id}: all {len(rejected)} target account(s) rejected "
                    f"scheduled publish — {[r.get('reason') for r in rejected]}"
                )
                audit.write_audit_log(
                    session,
                    tenant_id=tenant.id,
                    entity_type="content_piece",
                    entity_id=piece.id,
                    action="scheduled_publish_all_rejected",
                    actor="system:automation_scheduler",
                )
        except Exception:
            # Uma piece problemática não pode derrubar o passe inteiro.
            session.rollback()
            logger.exception(
                f"piece {getattr(piece, 'id', None)}: scheduled-publish dispatch failed"
            )
            continue


_stop_event = threading.Event()
_scheduler_thread: Optional[threading.Thread] = None


def _tick() -> None:
    """Um tick roda os 3 passes em sequência, cada um em sua própria sessão.

    Ao contrário do dispatcher de publicação da fase 3, nenhum passe aqui
    precisa de um pool de threads próprio: a geração já é assíncrona por
    conta de pieces_service.create_piece/schedule_piece (fase 2), e a
    avaliação de regra e o disparo de publicação agendada são operações de
    banco rápidas — o trabalho pesado sempre acontece em outro lugar.
    """
    # Cada passe é isolado: um passe que estoure não pode impedir os outros
    # dois de rodar neste tick (e, como nada remove a linha ofensora da
    # elegibilidade, o mesmo estouro se repetiria em todos os ticks seguintes).
    for name, pass_fn in (
        ("generation", _fill_campaign_calendars),
        ("approval", _evaluate_pending_approvals),
        ("publish_dispatch", _dispatch_scheduled_publications),
    ):
        try:
            with Session(get_engine()) as session:
                pass_fn(session, batch_limit=_BATCH_LIMIT)
        except Exception:
            logger.exception(f"automation scheduler pass '{name}' failed")


def _loop() -> None:
    while not _stop_event.is_set():
        try:
            _tick()
        except Exception:
            logger.exception("automation scheduler tick failed")
        _stop_event.wait(TICK_SECONDS)


def start_scheduler() -> None:
    global _scheduler_thread
    if _scheduler_thread is not None:
        return
    _stop_event.clear()
    _scheduler_thread = threading.Thread(
        target=_loop, name="mpt-content-automation-scheduler", daemon=True
    )
    _scheduler_thread.start()


def stop_scheduler() -> None:
    global _scheduler_thread
    _stop_event.set()
    if _scheduler_thread is not None:
        _scheduler_thread.join(timeout=5)
        _scheduler_thread = None
