"""add generation engine tables

Revision ID: 574ed629fa1f
Revises: 60a7421f3570
Create Date: 2026-08-27 22:08:05.278769

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '574ed629fa1f'
down_revision = '60a7421f3570'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_generation_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('image', 'video', 'voice', name='content_generation_provider_kind'), nullable=True),
    sa.Column('provider', sa.Enum('wavespeed', 'falai', 'gemini', 'elevenlabs', name='content_generation_provider_name'), nullable=True),
    sa.Column('credentials_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['content_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_generation_providers_tenant_id'), 'content_generation_providers', ['tenant_id'], unique=False)
    op.create_table('content_avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('voice_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('voice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['content_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_avatars_client_id'), 'content_avatars', ['client_id'], unique=False)
    op.create_table('content_generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('content_piece_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('image', 'video', 'voice', name='content_generation_job_kind'), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'retrying', 'completed', 'failed', 'cancelled', 'timeout', name='content_generation_job_status'), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_metadata', sa.JSON(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('input_units', sa.Float(), nullable=True),
    sa.Column('output_units', sa.Float(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['content_clients.id'], ),
    sa.ForeignKeyConstraint(['content_piece_id'], ['content_pieces.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['content_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_generation_jobs_client_id'), 'content_generation_jobs', ['client_id'], unique=False)
    op.create_index(op.f('ix_content_generation_jobs_content_piece_id'), 'content_generation_jobs', ['content_piece_id'], unique=False)
    op.create_index(op.f('ix_content_generation_jobs_tenant_id'), 'content_generation_jobs', ['tenant_id'], unique=False)
    op.create_table('content_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('content_piece_id', sa.Integer(), nullable=False),
    sa.Column('generation_job_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('image', 'audio', 'video', 'thumbnail', 'subtitle', name='content_asset_type'), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_intermediate', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['content_clients.id'], ),
    sa.ForeignKeyConstraint(['content_piece_id'], ['content_pieces.id'], ),
    sa.ForeignKeyConstraint(['generation_job_id'], ['content_generation_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['content_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_assets_client_id'), 'content_assets', ['client_id'], unique=False)
    op.create_index(op.f('ix_content_assets_content_piece_id'), 'content_assets', ['content_piece_id'], unique=False)
    op.create_index(op.f('ix_content_assets_generation_job_id'), 'content_assets', ['generation_job_id'], unique=False)
    op.create_index(op.f('ix_content_assets_tenant_id'), 'content_assets', ['tenant_id'], unique=False)
    op.add_column('content_pieces', sa.Column('generation_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('content_pieces', sa.Column('avatar_id', sa.Integer(), nullable=True))
    op.add_column('content_pieces', sa.Column('source_image_piece_id', sa.Integer(), nullable=True))
    op.add_column('content_pieces', sa.Column('voice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('content_pieces', sa.Column('is_synthetic_media', sa.Boolean(), server_default=sa.false(), nullable=False))
    content_category_enum = sa.Enum('medical', 'pharmaceutical', 'financial', 'insurance', 'legal', 'alcohol', 'gambling', 'political', 'regulated_product', name='content_category')
    content_category_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('content_pieces', sa.Column('content_category', content_category_enum, nullable=True))
    content_risk_level_enum = sa.Enum('none', 'low', 'medium', 'high', name='content_risk_level')
    content_risk_level_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('content_pieces', sa.Column('risk_level', content_risk_level_enum, server_default='none', nullable=False))
    op.add_column('content_pieces', sa.Column('requires_human_review', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('content_pieces', sa.Column('policy_version', sqlmodel.sql.sqltypes.AutoString(), server_default='v1', nullable=False))
    op.create_foreign_key('content_pieces_source_image_piece_id_fkey', 'content_pieces', 'content_pieces', ['source_image_piece_id'], ['id'])
    op.create_foreign_key('content_pieces_avatar_id_fkey', 'content_pieces', 'content_avatars', ['avatar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('content_pieces_avatar_id_fkey', 'content_pieces', type_='foreignkey')
    op.drop_constraint('content_pieces_source_image_piece_id_fkey', 'content_pieces', type_='foreignkey')
    op.drop_column('content_pieces', 'policy_version')
    op.drop_column('content_pieces', 'requires_human_review')
    op.drop_column('content_pieces', 'risk_level')
    sa.Enum(name='content_risk_level').drop(op.get_bind(), checkfirst=True)
    op.drop_column('content_pieces', 'content_category')
    sa.Enum(name='content_category').drop(op.get_bind(), checkfirst=True)
    op.drop_column('content_pieces', 'is_synthetic_media')
    op.drop_column('content_pieces', 'voice_id')
    op.drop_column('content_pieces', 'source_image_piece_id')
    op.drop_column('content_pieces', 'avatar_id')
    op.drop_column('content_pieces', 'generation_prompt')
    op.drop_index(op.f('ix_content_assets_tenant_id'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_generation_job_id'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_content_piece_id'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_client_id'), table_name='content_assets')
    op.drop_table('content_assets')
    sa.Enum(name='content_asset_type').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_content_generation_jobs_tenant_id'), table_name='content_generation_jobs')
    op.drop_index(op.f('ix_content_generation_jobs_content_piece_id'), table_name='content_generation_jobs')
    op.drop_index(op.f('ix_content_generation_jobs_client_id'), table_name='content_generation_jobs')
    op.drop_table('content_generation_jobs')
    sa.Enum(name='content_generation_job_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='content_generation_job_kind').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_content_avatars_client_id'), table_name='content_avatars')
    op.drop_table('content_avatars')
    op.drop_index(op.f('ix_content_generation_providers_tenant_id'), table_name='content_generation_providers')
    op.drop_table('content_generation_providers')
    sa.Enum(name='content_generation_provider_name').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='content_generation_provider_kind').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
