"""create content module tables

Revision ID: 60a7421f3570
Revises: 
Create Date: 2026-08-27 18:17:41.495090

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '60a7421f3570'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entitlement_status', sa.Enum('active', 'inactive', 'trial', name='content_entitlement_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_tenants_api_token_hash'), 'content_tenants', ['api_token_hash'], unique=True)
    op.create_index(op.f('ix_content_tenants_owner_user_id'), 'content_tenants', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_content_tenants_slug'), 'content_tenants', ['slug'], unique=True)
    op.create_table('content_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['content_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_audit_logs_tenant_id'), 'content_audit_logs', ['tenant_id'], unique=False)
    op.create_table('content_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['content_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_clients_tenant_id'), 'content_clients', ['tenant_id'], unique=False)
    op.create_table('content_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['content_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_campaigns_client_id'), 'content_campaigns', ['client_id'], unique=False)
    op.create_table('content_social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credentials_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['content_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_social_accounts_client_id'), 'content_social_accounts', ['client_id'], unique=False)
    op.create_table('content_approval_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.Column('action', sa.Enum('auto_approve', 'require_review', name='content_approval_action'), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['content_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_approval_rules_campaign_id'), 'content_approval_rules', ['campaign_id'], unique=False)
    op.create_table('content_pieces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('video', 'image', 'audio', name='content_piece_type'), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'rejected', 'posted', 'failed', name='content_piece_status'), nullable=True),
    sa.Column('asset_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['content_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_pieces_campaign_id'), 'content_pieces', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_content_pieces_idempotency_key'), 'content_pieces', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_pieces_idempotency_key'), table_name='content_pieces')
    op.drop_index(op.f('ix_content_pieces_campaign_id'), table_name='content_pieces')
    op.drop_table('content_pieces')
    op.drop_index(op.f('ix_content_approval_rules_campaign_id'), table_name='content_approval_rules')
    op.drop_table('content_approval_rules')
    op.drop_index(op.f('ix_content_social_accounts_client_id'), table_name='content_social_accounts')
    op.drop_table('content_social_accounts')
    op.drop_index(op.f('ix_content_campaigns_client_id'), table_name='content_campaigns')
    op.drop_table('content_campaigns')
    op.drop_index(op.f('ix_content_clients_tenant_id'), table_name='content_clients')
    op.drop_table('content_clients')
    op.drop_index(op.f('ix_content_audit_logs_tenant_id'), table_name='content_audit_logs')
    op.drop_table('content_audit_logs')
    op.drop_index(op.f('ix_content_tenants_slug'), table_name='content_tenants')
    op.drop_index(op.f('ix_content_tenants_owner_user_id'), table_name='content_tenants')
    op.drop_index(op.f('ix_content_tenants_api_token_hash'), table_name='content_tenants')
    op.drop_table('content_tenants')
    # ### end Alembic commands ###
