"""add automation and approval tables

Revision ID: e4c2a9f1b6d3
Revises: b6a1f9c3d2e7
Create Date: 2026-08-29 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e4c2a9f1b6d3'
down_revision = 'b6a1f9c3d2e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        'content_generation_templates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('campaign_id', sa.Integer(), nullable=False),
        sa.Column(
            'type',
            sa.Enum('video', 'image', 'audio', name='content_piece_type', create_type=False),
            nullable=True,
        ),
        sa.Column('generation_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('avatar_id', sa.Integer(), nullable=True),
        sa.Column('voice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('is_synthetic_media', sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column(
            'content_category',
            sa.Enum(
                'medical', 'pharmaceutical', 'financial', 'insurance', 'legal',
                'alcohol', 'gambling', 'political', 'regulated_product',
                name='content_category', create_type=False,
            ),
            nullable=True,
        ),
        sa.Column('aspect_ratio', sqlmodel.sql.sqltypes.AutoString(), server_default='9:16', nullable=False),
        sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('duration', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['avatar_id'], ['content_avatars.id'], ),
        sa.ForeignKeyConstraint(['campaign_id'], ['content_campaigns.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_content_generation_templates_campaign_id'),
        'content_generation_templates', ['campaign_id'], unique=False,
    )

    op.add_column('content_pieces', sa.Column(
        'approval_action',
        sa.Enum('auto_approve', 'require_review', name='content_approval_action', create_type=False),
        nullable=True,
    ))
    op.add_column('content_pieces', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('content_pieces', sa.Column(
        'is_autogenerated', sa.Boolean(), server_default=sa.false(), nullable=False,
    ))


def downgrade() -> None:
    op.drop_column('content_pieces', 'is_autogenerated')
    op.drop_column('content_pieces', 'approved_at')
    op.drop_column('content_pieces', 'approval_action')
    op.drop_index(
        op.f('ix_content_generation_templates_campaign_id'),
        table_name='content_generation_templates',
    )
    op.drop_table('content_generation_templates')
