import unittest
from datetime import datetime, timedelta
from unittest.mock import MagicMock, patch

from sqlalchemy.exc import IntegrityError

from app.models.content import ContentPieceType, EntitlementStatus
from app.services.content import automation_scheduler as scheduler
from app.services.content import generation_templates as templates_service
from app.services.content import pieces as pieces_service


class TestNextSlot(unittest.TestCase):
    def test_no_existing_pieces_returns_now(self):
        now = datetime(2026, 8, 29, 10, 0, 0)

        result = scheduler.next_slot(None, now=now)

        self.assertEqual(result, now)

    def test_existing_max_scheduled_advances_by_one_day(self):
        max_scheduled = datetime(2026, 8, 30, 10, 0, 0)
        now = datetime(2026, 8, 29, 10, 0, 0)

        result = scheduler.next_slot(max_scheduled, now=now)

        self.assertEqual(result, max_scheduled + timedelta(days=1))


class TestPickTemplateIndex(unittest.TestCase):
    def test_rotates_through_templates_in_order(self):
        self.assertEqual(scheduler.pick_template_index(0, 3), 0)
        self.assertEqual(scheduler.pick_template_index(1, 3), 1)
        self.assertEqual(scheduler.pick_template_index(2, 3), 2)
        self.assertEqual(scheduler.pick_template_index(3, 3), 0)
        self.assertEqual(scheduler.pick_template_index(7, 3), 1)

    def test_single_template_always_picks_it(self):
        self.assertEqual(scheduler.pick_template_index(0, 1), 0)
        self.assertEqual(scheduler.pick_template_index(50, 1), 0)


class TestFillCampaignCalendars(unittest.TestCase):
    def _campaign(self, **overrides):
        base = dict(id=1, client_id=1, horizon_days=7, status="active")
        base.update(overrides)
        return MagicMock(**base)

    def _tenant(self, **overrides):
        base = dict(id=1, entitlement_status=EntitlementStatus.active)
        base.update(overrides)
        return MagicMock(**base)

    def _client(self, tenant_id=1):
        return MagicMock(id=1, tenant_id=tenant_id)

    def test_skips_campaign_with_no_templates(self):
        session = MagicMock()
        campaign = self._campaign()
        session.exec.return_value.all.side_effect = [[campaign], []]
        session.get.side_effect = lambda model, id_: {
            ("ContentClient", 1): self._client(),
            ("ContentTenant", 1): self._tenant(),
        }.get((model.__name__, id_))

        with patch.object(templates_service, "list_templates", return_value=[]):
            with patch.object(pieces_service, "create_piece") as create_piece:
                scheduler._fill_campaign_calendars(session, batch_limit=50)

        create_piece.assert_not_called()

    def test_skips_campaign_when_tenant_not_active(self):
        session = MagicMock()
        campaign = self._campaign()
        session.exec.return_value.all.side_effect = [[campaign], []]
        session.get.side_effect = lambda model, id_: {
            ("ContentClient", 1): self._client(),
            ("ContentTenant", 1): self._tenant(entitlement_status=EntitlementStatus.inactive),
        }.get((model.__name__, id_))

        with patch.object(pieces_service, "create_piece") as create_piece:
            scheduler._fill_campaign_calendars(session, batch_limit=50)

        create_piece.assert_not_called()

    def test_creates_one_piece_from_rotated_template_when_horizon_not_full(self):
        session = MagicMock()
        campaign = self._campaign(horizon_days=7)
        template = MagicMock(
            id=9,
            type=ContentPieceType.image,
            generation_prompt="a cat",
            avatar_id=None,
            voice_id=None,
            is_synthetic_media=False,
            content_category=None,
            aspect_ratio="9:16",
            resolution=None,
            duration=None,
        )
        # First query: active campaigns. Second: no existing non-terminal
        # pieces for max_scheduled. Third: 0 autogenerated pieces so far.
        session.exec.return_value.all.side_effect = [[campaign], [], []]
        session.exec.return_value.first.return_value = None
        session.get.side_effect = lambda model, id_: {
            ("ContentClient", 1): self._client(),
            ("ContentTenant", 1): self._tenant(),
        }.get((model.__name__, id_))
        created_piece = MagicMock(id=100)

        with patch.object(templates_service, "list_templates", return_value=[template]):
            with patch.object(
                pieces_service, "create_piece", return_value=(created_piece, True)
            ) as create_piece:
                scheduler._fill_campaign_calendars(session, batch_limit=50)

        create_piece.assert_called_once()
        _, kwargs = create_piece.call_args
        self.assertEqual(kwargs["tenant_id"], 1)
        payload = kwargs["payload"]
        self.assertEqual(payload.campaign_id, 1)
        self.assertEqual(payload.type, ContentPieceType.image)
        self.assertTrue(payload.idempotency_key.startswith("auto:1:"))
        self.assertTrue(created_piece.is_autogenerated)
        session.add.assert_any_call(created_piece)

    def test_integrity_error_on_one_campaign_does_not_stop_the_batch(self):
        session = MagicMock()
        campaign_a = self._campaign(id=1, client_id=1)
        campaign_b = self._campaign(id=2, client_id=1)
        template = MagicMock(
            id=9,
            type=ContentPieceType.image,
            generation_prompt="a cat",
            avatar_id=None,
            voice_id=None,
            is_synthetic_media=False,
            content_category=None,
            aspect_ratio="9:16",
            resolution=None,
            duration=None,
        )
        session.exec.return_value.all.side_effect = [
            [campaign_a, campaign_b], [], [], [], [],
        ]
        # Without this, session.exec(...).first() returns a default MagicMock
        # (not None), and the horizon-check comparison against a real
        # datetime raises TypeError before create_piece is ever reached.
        session.exec.return_value.first.return_value = None
        session.get.side_effect = lambda model, id_: {
            ("ContentClient", 1): self._client(),
            ("ContentTenant", 1): self._tenant(),
        }.get((model.__name__, id_))
        created_piece = MagicMock(id=101)

        with patch.object(templates_service, "list_templates", return_value=[template]):
            with patch.object(
                pieces_service,
                "create_piece",
                side_effect=[IntegrityError("stmt", {}, Exception("dup")), (created_piece, True)],
            ) as create_piece:
                scheduler._fill_campaign_calendars(session, batch_limit=50)

        self.assertEqual(create_piece.call_count, 2)
        session.rollback.assert_called_once()


if __name__ == "__main__":
    unittest.main()
