import unittest
from datetime import datetime
from unittest.mock import patch

from sqlmodel import Session, SQLModel, create_engine, select

from app.models import content_publishing  # noqa: F401  (registers tables in metadata)
from app.models.content import (
    ApprovalAction,
    ContentApprovalRule,
    ContentCampaign,
    ContentClient,
    ContentGenerationTemplate,
    ContentPiece,
    ContentPieceStatus,
    ContentPieceType,
    ContentSocialAccount,
    ContentTenant,
    EntitlementStatus,
    RiskLevel,
)
from app.models.content_generation import ContentAsset, ContentAssetType
from app.models.content_publishing import ContentSocialPublication, PublicationStatus
from app.services.content import automation_scheduler as scheduler
from app.services.content import pieces as pieces_service


def _create_piece_as_if_generated(session, *, payload):
    """Stand-in for pieces_service.create_piece that skips the async
    generation call (out of scope here — covered separately by the pipeline
    tests) but otherwise behaves like generation already finished: a real
    row lands in the database at `pending_approval`, exactly what Pass 2
    needs to find it.
    """
    piece = ContentPiece(
        campaign_id=payload.campaign_id,
        type=payload.type,
        status=ContentPieceStatus.pending_approval,
        generation_prompt=payload.generation_prompt,
        idempotency_key=payload.idempotency_key,
        content_category=payload.content_category,
        risk_level=RiskLevel.none,
        requires_human_review=False,
        updated_at=datetime.utcnow(),
    )
    session.add(piece)
    session.commit()
    session.refresh(piece)
    return piece, True


class TestSchedulerThreePassChain(unittest.TestCase):
    """Runs Pass 1 (proactive generation) -> Pass 2 (approval evaluation) ->
    Pass 3 (scheduled-publish dispatch) against a real SQLite engine, one
    piece flowing through all three — the seam no existing test exercises
    (every test in test_content_automation_scheduler.py mocks the session).
    Only the generation-provider boundary is mocked (via
    _create_piece_as_if_generated); everything else, including the approval
    rule match and the publish-request resolution, runs for real.
    """

    def setUp(self):
        engine = create_engine("sqlite://")
        SQLModel.metadata.create_all(engine)
        self.session = Session(engine)
        self.addCleanup(self.session.close)

        tenant = ContentTenant(
            owner_user_id="u1", name="T", slug="t", api_token_hash="h",
            entitlement_status=EntitlementStatus.active,
        )
        self.session.add(tenant)
        self.session.commit()
        self.client = ContentClient(tenant_id=tenant.id, name="C")
        self.session.add(self.client)
        self.session.commit()
        self.campaign = ContentCampaign(
            client_id=self.client.id, name="Camp", horizon_days=7, status="active"
        )
        self.session.add(self.campaign)
        self.session.commit()
        self.session.add(
            ContentGenerationTemplate(
                campaign_id=self.campaign.id,
                type=ContentPieceType.image,
                generation_prompt="a cat",
            )
        )
        self.session.add(
            ContentApprovalRule(
                campaign_id=self.campaign.id, condition={}, action=ApprovalAction.auto_approve
            )
        )
        self.account = ContentSocialAccount(
            client_id=self.client.id, platform="x", external_account_id="acc-1",
            credentials_encrypted="enc", status="active",
        )
        self.session.add(self.account)
        self.session.commit()

    def _only_piece(self) -> ContentPiece:
        pieces = self.session.exec(select(ContentPiece)).all()
        self.assertEqual(len(pieces), 1, "expected exactly one piece to have been created")
        return pieces[0]

    def test_piece_flows_from_generation_through_approval_to_publish_dispatch(self):
        with patch.object(
            pieces_service, "create_piece", side_effect=_create_piece_as_if_generated
        ):
            scheduler._fill_campaign_calendars(self.session, batch_limit=50)

        piece = self._only_piece()
        self.assertEqual(piece.status, ContentPieceStatus.pending_approval)
        self.assertTrue(piece.is_autogenerated)
        self.assertIsNotNone(piece.scheduled_for)

        scheduler._evaluate_pending_approvals(self.session, batch_limit=50)

        self.session.refresh(piece)
        self.assertEqual(piece.status, ContentPieceStatus.approved)
        self.assertEqual(piece.approval_action, ApprovalAction.auto_approve)

        self.session.add(
            ContentAsset(
                tenant_id=self.client.tenant_id,
                client_id=self.client.id,
                content_piece_id=piece.id,
                type=ContentAssetType.image,
                url="https://x/asset.png",
                is_intermediate=False,
            )
        )
        self.session.commit()

        scheduler._dispatch_scheduled_publications(self.session, batch_limit=50)

        publications = self.session.exec(select(ContentSocialPublication)).all()
        self.assertEqual(len(publications), 1)
        self.assertEqual(publications[0].content_piece_id, piece.id)
        self.assertEqual(publications[0].social_account_id, self.account.id)
        self.assertEqual(publications[0].status, PublicationStatus.queued)

    def test_pass_2_skips_a_piece_not_yet_pending_approval(self):
        """Pass 1 alone must not make a piece eligible for dispatch — Pass 2
        has to run and approve it first. Proves the passes are actually
        gated on each other, not just independently correct."""
        with patch.object(
            pieces_service, "create_piece", side_effect=_create_piece_as_if_generated
        ):
            scheduler._fill_campaign_calendars(self.session, batch_limit=50)

        piece = self._only_piece()
        self.session.add(
            ContentAsset(
                tenant_id=self.client.tenant_id,
                client_id=self.client.id,
                content_piece_id=piece.id,
                type=ContentAssetType.image,
                url="https://x/asset.png",
                is_intermediate=False,
            )
        )
        self.session.commit()

        # Pass 3 runs without Pass 2 ever having approved the piece.
        scheduler._dispatch_scheduled_publications(self.session, batch_limit=50)

        publications = self.session.exec(select(ContentSocialPublication)).all()
        self.assertEqual(publications, [])


if __name__ == "__main__":
    unittest.main()
