import unittest
from datetime import datetime, timedelta
from unittest.mock import MagicMock, patch

from sqlalchemy.dialects import postgresql
from sqlalchemy.exc import IntegrityError

from app.models.content import (
    ApprovalAction,
    ContentCategory,
    ContentPieceStatus,
    ContentPieceType,
    EntitlementStatus,
    RiskLevel,
)
from app.services.content import approval_rules as approval_rules_service
from app.services.content import automation_scheduler as scheduler
from app.services.content import generation_templates as templates_service
from app.services.content import pieces as pieces_service


class TestNextSlot(unittest.TestCase):
    def test_no_existing_pieces_returns_now(self):
        now = datetime(2026, 8, 29, 10, 0, 0)

        result = scheduler.next_slot(None, now=now)

        self.assertEqual(result, now)

    def test_existing_max_scheduled_advances_by_one_day(self):
        max_scheduled = datetime(2026, 8, 30, 10, 0, 0)
        now = datetime(2026, 8, 29, 10, 0, 0)

        result = scheduler.next_slot(max_scheduled, now=now)

        self.assertEqual(result, max_scheduled + timedelta(days=1))


class TestPickTemplateIndex(unittest.TestCase):
    def test_rotates_through_templates_in_order(self):
        self.assertEqual(scheduler.pick_template_index(0, 3), 0)
        self.assertEqual(scheduler.pick_template_index(1, 3), 1)
        self.assertEqual(scheduler.pick_template_index(2, 3), 2)
        self.assertEqual(scheduler.pick_template_index(3, 3), 0)
        self.assertEqual(scheduler.pick_template_index(7, 3), 1)

    def test_single_template_always_picks_it(self):
        self.assertEqual(scheduler.pick_template_index(0, 1), 0)
        self.assertEqual(scheduler.pick_template_index(50, 1), 0)


class TestFillCampaignCalendars(unittest.TestCase):
    def _campaign(self, **overrides):
        base = dict(id=1, client_id=1, horizon_days=7, status="active")
        base.update(overrides)
        return MagicMock(**base)

    def _tenant(self, **overrides):
        base = dict(id=1, entitlement_status=EntitlementStatus.active)
        base.update(overrides)
        return MagicMock(**base)

    def _client(self, tenant_id=1):
        return MagicMock(id=1, tenant_id=tenant_id)

    def test_skips_campaign_with_no_templates(self):
        session = MagicMock()
        campaign = self._campaign()
        session.exec.return_value.all.side_effect = [[campaign], []]
        session.get.side_effect = lambda model, id_: {
            ("ContentClient", 1): self._client(),
            ("ContentTenant", 1): self._tenant(),
        }.get((model.__name__, id_))

        with patch.object(templates_service, "list_templates", return_value=[]):
            with patch.object(pieces_service, "create_piece") as create_piece:
                scheduler._fill_campaign_calendars(session, batch_limit=50)

        create_piece.assert_not_called()

    def test_skips_campaign_when_tenant_not_active(self):
        session = MagicMock()
        campaign = self._campaign()
        session.exec.return_value.all.side_effect = [[campaign], []]
        session.get.side_effect = lambda model, id_: {
            ("ContentClient", 1): self._client(),
            ("ContentTenant", 1): self._tenant(entitlement_status=EntitlementStatus.inactive),
        }.get((model.__name__, id_))

        with patch.object(pieces_service, "create_piece") as create_piece:
            scheduler._fill_campaign_calendars(session, batch_limit=50)

        create_piece.assert_not_called()

    def test_creates_one_piece_from_rotated_template_when_horizon_not_full(self):
        session = MagicMock()
        campaign = self._campaign(horizon_days=7)
        template = MagicMock(
            id=9,
            type=ContentPieceType.image,
            generation_prompt="a cat",
            avatar_id=None,
            voice_id=None,
            is_synthetic_media=False,
            content_category=None,
            aspect_ratio="9:16",
            resolution=None,
            duration=None,
        )
        # First query: active campaigns. Second: no existing non-terminal
        # pieces for max_scheduled. Third: 0 autogenerated pieces so far.
        session.exec.return_value.all.side_effect = [[campaign], [], []]
        session.exec.return_value.first.return_value = None
        session.get.side_effect = lambda model, id_: {
            ("ContentClient", 1): self._client(),
            ("ContentTenant", 1): self._tenant(),
        }.get((model.__name__, id_))
        created_piece = MagicMock(id=100)

        with patch.object(templates_service, "list_templates", return_value=[template]):
            with patch.object(
                pieces_service, "create_piece", return_value=(created_piece, True)
            ) as create_piece:
                scheduler._fill_campaign_calendars(session, batch_limit=50)

        create_piece.assert_called_once()
        _, kwargs = create_piece.call_args
        self.assertEqual(kwargs["tenant_id"], 1)
        payload = kwargs["payload"]
        self.assertEqual(payload.campaign_id, 1)
        self.assertEqual(payload.type, ContentPieceType.image)
        self.assertTrue(payload.idempotency_key.startswith("auto:1:"))
        self.assertTrue(created_piece.is_autogenerated)
        session.add.assert_any_call(created_piece)

    def test_integrity_error_on_one_campaign_does_not_stop_the_batch(self):
        session = MagicMock()
        campaign_a = self._campaign(id=1, client_id=1)
        campaign_b = self._campaign(id=2, client_id=1)
        template = MagicMock(
            id=9,
            type=ContentPieceType.image,
            generation_prompt="a cat",
            avatar_id=None,
            voice_id=None,
            is_synthetic_media=False,
            content_category=None,
            aspect_ratio="9:16",
            resolution=None,
            duration=None,
        )
        session.exec.return_value.all.side_effect = [
            [campaign_a, campaign_b], [], [], [], [],
        ]
        # Without this, session.exec(...).first() returns a default MagicMock
        # (not None), and the horizon-check comparison against a real
        # datetime raises TypeError before create_piece is ever reached.
        session.exec.return_value.first.return_value = None
        session.get.side_effect = lambda model, id_: {
            ("ContentClient", 1): self._client(),
            ("ContentTenant", 1): self._tenant(),
        }.get((model.__name__, id_))
        created_piece = MagicMock(id=101)

        with patch.object(templates_service, "list_templates", return_value=[template]):
            with patch.object(
                pieces_service,
                "create_piece",
                side_effect=[IntegrityError("stmt", {}, Exception("dup")), (created_piece, True)],
            ) as create_piece:
                scheduler._fill_campaign_calendars(session, batch_limit=50)

        self.assertEqual(create_piece.call_count, 2)
        session.rollback.assert_called_once()


class TestRuleMatches(unittest.TestCase):
    def test_empty_condition_matches_anything(self):
        self.assertTrue(
            scheduler.rule_matches(
                {}, content_category=ContentCategory.medical, risk_level=RiskLevel.high
            )
        )
        self.assertTrue(
            scheduler.rule_matches({}, content_category=None, risk_level=RiskLevel.none)
        )

    def test_matches_when_risk_level_in_allowed_list(self):
        condition = {"risk_level": ["high", "medium"]}

        self.assertTrue(
            scheduler.rule_matches(
                condition, content_category=None, risk_level=RiskLevel.high
            )
        )
        self.assertFalse(
            scheduler.rule_matches(
                condition, content_category=None, risk_level=RiskLevel.low
            )
        )

    def test_matches_when_content_category_in_allowed_list(self):
        condition = {"content_category": ["financial", "insurance"]}

        self.assertTrue(
            scheduler.rule_matches(
                condition, content_category=ContentCategory.financial, risk_level=RiskLevel.none
            )
        )
        self.assertFalse(
            scheduler.rule_matches(
                condition, content_category=None, risk_level=RiskLevel.none
            )
        )

    def test_multiple_keys_require_all_to_match(self):
        condition = {"content_category": ["financial"], "risk_level": ["high"]}

        self.assertTrue(
            scheduler.rule_matches(
                condition, content_category=ContentCategory.financial, risk_level=RiskLevel.high
            )
        )
        self.assertFalse(
            scheduler.rule_matches(
                condition, content_category=ContentCategory.financial, risk_level=RiskLevel.medium
            )
        )

    def test_unsupported_condition_key_never_matches(self):
        condition = {"type": ["video"]}

        self.assertFalse(
            scheduler.rule_matches(
                condition, content_category=None, risk_level=RiskLevel.none
            )
        )


class TestEvaluatePendingApprovals(unittest.TestCase):
    def _piece(self, **overrides):
        base = dict(
            id=1,
            campaign_id=1,
            status=ContentPieceStatus.pending_approval,
            requires_human_review=False,
            content_category=None,
            risk_level=RiskLevel.none,
        )
        base.update(overrides)
        return MagicMock(**base)

    def _client_and_tenant(self):
        return MagicMock(id=1, tenant_id=1), MagicMock(id=1)

    def test_requires_human_review_always_wins_over_rules(self):
        piece = self._piece(requires_human_review=True)
        session = MagicMock()
        session.exec.return_value.all.return_value = [piece]
        session.exec.return_value.rowcount = 1
        client, _ = self._client_and_tenant()
        session.get.side_effect = lambda model, id_: {
            ("ContentCampaign", 1): MagicMock(id=1, client_id=1),
            ("ContentClient", 1): client,
        }.get((model.__name__, id_))

        with patch.object(approval_rules_service, "list_approval_rules") as list_rules:
            scheduler._evaluate_pending_approvals(session, batch_limit=50)

        list_rules.assert_not_called()
        session.commit.assert_called()

        # Regression guard: the mocked rowcount above proves nothing about
        # what predicate actually reached the DB. Compile the real statement
        # passed to session.exec and assert the WHERE clause still ANDs both
        # the id and the pending_approval status — a future edit that drops
        # the status predicate would still pass every assertion above.
        update_call = session.exec.call_args_list[-1].args[0]
        compiled = str(
            update_call.compile(
                dialect=postgresql.dialect(), compile_kwargs={"literal_binds": True}
            )
        ).upper()
        self.assertIn("STATUS = 'PENDING_APPROVAL'", compiled)
        self.assertIn("ID = 1", compiled)

    def test_matching_rule_auto_approves(self):
        piece = self._piece(risk_level=RiskLevel.high)
        rule = MagicMock(
            condition={"risk_level": ["high"]}, action=ApprovalAction.auto_approve, priority=10
        )
        session = MagicMock()
        session.exec.return_value.all.return_value = [piece]
        session.exec.return_value.rowcount = 1
        client, _ = self._client_and_tenant()
        session.get.side_effect = lambda model, id_: {
            ("ContentCampaign", 1): MagicMock(id=1, client_id=1),
            ("ContentClient", 1): client,
        }.get((model.__name__, id_))

        with patch.object(approval_rules_service, "list_approval_rules", return_value=[rule]):
            scheduler._evaluate_pending_approvals(session, batch_limit=50)

        session.commit.assert_called()

    def test_no_matching_rule_defaults_to_require_review(self):
        piece = self._piece()
        rule = MagicMock(
            condition={"risk_level": ["high"]}, action=ApprovalAction.auto_approve, priority=10
        )
        session = MagicMock()
        session.exec.return_value.all.return_value = [piece]
        session.exec.return_value.rowcount = 1
        client, _ = self._client_and_tenant()
        session.get.side_effect = lambda model, id_: {
            ("ContentCampaign", 1): MagicMock(id=1, client_id=1),
            ("ContentClient", 1): client,
        }.get((model.__name__, id_))

        with patch.object(approval_rules_service, "list_approval_rules", return_value=[rule]):
            scheduler._evaluate_pending_approvals(session, batch_limit=50)

        session.commit.assert_called()

    def test_concurrent_status_change_drops_the_decision_without_error(self):
        piece = self._piece()
        session = MagicMock()
        session.exec.return_value.all.return_value = [piece]
        session.exec.return_value.rowcount = 0
        client, _ = self._client_and_tenant()
        session.get.side_effect = lambda model, id_: {
            ("ContentCampaign", 1): MagicMock(id=1, client_id=1),
            ("ContentClient", 1): client,
        }.get((model.__name__, id_))

        with patch.object(approval_rules_service, "list_approval_rules", return_value=[]):
            scheduler._evaluate_pending_approvals(session, batch_limit=50)

        # Regression guard: rowcount=0 here simulates the race being caught,
        # but only if the guard's WHERE clause actually carries both
        # predicates. Compile the real statement so a future edit that drops
        # the status predicate (and thus stops the guard from ever
        # protecting anything) fails this test instead of staying green.
        update_call = session.exec.call_args_list[-1].args[0]
        compiled = str(
            update_call.compile(
                dialect=postgresql.dialect(), compile_kwargs={"literal_binds": True}
            )
        ).upper()
        self.assertIn("STATUS = 'PENDING_APPROVAL'", compiled)
        self.assertIn("ID = 1", compiled)


if __name__ == "__main__":
    unittest.main()
