import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { Bot, Send, Sparkles } from "lucide-react";
import { apiClient } from "../lib/apiClient";
import { parseUtc } from "../lib/calendarDates";
import type { AgentProposal, AuditLogEntry } from "../lib/types";
import { Button } from "../components/ui/Button";
import { Card, MicroLabel } from "../components/ui/Card";
import { EmptyState, SkeletonRows } from "../components/ui/Feedback";
import { cn } from "../components/ui/cn";

const QUICK_BRIEFS = [
  "Planeje uma semana sobre longevidade e exames de rotina",
  "Crie 3 posts explicando mitos de suplementação",
  "Série sobre sono: o que tem evidência",
];

/** Human-readable names for the automation's own audit actions. */
const ACTION_LABEL: Record<string, string> = {
  autogenerated: "Gerou uma peça proativamente",
  "approval_action:auto_approve": "Aprovou automaticamente",
  "approval_action:require_review": "Encaminhou para revisão humana",
  scheduled_publish_all_rejected: "Publicação agendada recusada por todas as contas",
  generation_queue_saturated: "Fila de geração saturada",
};

function actionLabel(action: string): string {
  return ACTION_LABEL[action] ?? action;
}

export function SocialAgent() {
  const [brief, setBrief] = useState("");
  const [proposal, setProposal] = useState<AgentProposal | null>(null);

  const activity = useQuery({
    queryKey: ["agent", "activity"],
    queryFn: () =>
      apiClient.get<AuditLogEntry[]>("/content/ui/agent/activity?limit=30"),
  });

  const propose = useMutation({
    mutationFn: (text: string) =>
      apiClient.post<AgentProposal>("/content/ui/agent/brief", { brief: text }),
    onSuccess: setProposal,
  });

  function submit(text: string) {
    const value = text.trim();
    if (!value) return;
    setBrief(value);
    propose.mutate(value);
  }

  return (
    <div className="flex flex-col gap-5">
      <div className="flex items-center gap-2">
        <Bot size={18} className="text-[var(--text-h)]" />
        <h1 className="m-0 text-[20px] font-semibold tracking-tight">Agente</h1>
      </div>

      <Card className="p-4 flex flex-col gap-3">
        <MicroLabel>Briefe o agente</MicroLabel>
        <div className="flex flex-col sm:flex-row gap-2">
          <input
            value={brief}
            onChange={(event) => setBrief(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === "Enter") submit(brief);
            }}
            placeholder="Descreva o que você quer publicar…"
            className="flex-1 h-9 rounded-[4px] border border-[var(--border)] bg-[var(--card-bg)] px-3 text-[13px] text-[var(--text-h)]"
          />
          <Button
            variant="primary"
            onClick={() => submit(brief)}
            disabled={propose.isPending || !brief.trim()}
          >
            <Send size={13} />
            {propose.isPending ? "Planejando…" : "Planejar"}
          </Button>
        </div>

        <div className="flex flex-wrap gap-1.5">
          {QUICK_BRIEFS.map((text) => (
            <button
              key={text}
              type="button"
              onClick={() => submit(text)}
              className="h-7 px-2.5 rounded-full border border-[var(--border)] bg-[var(--card-bg)] text-[12px] text-[var(--text)] hover:bg-[var(--code-bg)] hover:text-[var(--text-h)] cursor-pointer"
            >
              {text}
            </button>
          ))}
        </div>

        <p className="m-0 text-[12px] text-[var(--text)]">
          O agente <strong>propõe</strong> — nada é criado, agendado ou gerado até você
          confirmar.
        </p>
      </Card>

      {propose.isError ? (
        <Card className="p-3 border-bad text-[13px] text-bad">
          Não foi possível planejar a partir desse briefing.
        </Card>
      ) : null}

      {proposal ? (
        <Card className="p-4 flex flex-col gap-3">
          <div className="flex items-start justify-between gap-3">
            <div className="flex flex-col gap-1">
              <MicroLabel>Proposta</MicroLabel>
              <p className="m-0 text-[13px] text-[var(--text-h)]">{proposal.summary}</p>
            </div>
            <span className="shrink-0 font-mono text-[10px] text-[var(--text)]">
              {proposal.pieces.length} PEÇAS
            </span>
          </div>

          {proposal.is_fallback ? (
            <p className="m-0 rounded-[4px] border border-warn/40 bg-warn/5 px-2 py-1.5 text-[12px] text-warn">
              O modelo não respondeu — esta é uma proposta mínima montada a partir do
              briefing, não um plano gerado.
            </p>
          ) : null}

          <div className="flex flex-col gap-2">
            {proposal.pieces.map((piece, index) => (
              <div
                key={index}
                className="flex flex-col gap-1 rounded-[4px] border border-[var(--border)] p-2.5"
              >
                <div className="flex items-center gap-2">
                  <Sparkles size={12} className="text-[var(--text)]" />
                  <span className="font-mono text-[10px] uppercase tracking-[0.12em] text-[var(--text)]">
                    {piece.type}
                  </span>
                </div>
                <p className="m-0 text-[13px] text-[var(--text-h)]">
                  {piece.generation_prompt}
                </p>
                {piece.caption ? (
                  <p className="m-0 text-[12px] text-[var(--text)]">
                    Legenda: {piece.caption}
                  </p>
                ) : null}
              </div>
            ))}
          </div>
        </Card>
      ) : null}

      <div className="flex flex-col gap-2">
        <MicroLabel>O que o agente fez sozinho</MicroLabel>
        <Card className="p-0 overflow-hidden">
          {activity.isLoading ? (
            <div className="p-4">
              <SkeletonRows rows={4} />
            </div>
          ) : activity.isError ? (
            <EmptyState title="Não foi possível carregar a atividade" />
          ) : !activity.data || activity.data.length === 0 ? (
            <EmptyState
              title="Nenhuma decisão automática ainda"
              hint="Geração proativa, aprovações automáticas e disparos agendados aparecem aqui."
            />
          ) : (
            <ul className="m-0 list-none p-0 max-w-none">
              {activity.data.map((entry) => (
                <li
                  key={entry.id}
                  className={cn(
                    "flex flex-wrap items-center gap-2 px-3 py-2 text-[12px]",
                    "border-b border-[var(--border)] last:border-b-0",
                  )}
                >
                  <span className="font-mono text-[10px] text-[var(--text)]">
                    {parseUtc(entry.created_at).toLocaleString("pt-BR")}
                  </span>
                  <span className="flex-1 min-w-40 text-[var(--text-h)]">
                    {actionLabel(entry.action)}
                  </span>
                  {entry.entity_type === "content_piece" ? (
                    <Link
                      to={`/pieces/${entry.entity_id}`}
                      className="font-mono text-[11px] no-underline text-[var(--text)] hover:text-[var(--text-h)]"
                    >
                      #{entry.entity_id}
                    </Link>
                  ) : null}
                  <span className="font-mono text-[10px] text-[var(--text)]">
                    {entry.actor.replace("system:", "")}
                  </span>
                </li>
              ))}
            </ul>
          )}
        </Card>
      </div>
    </div>
  );
}
